### ISSUE TITLE
Enhance look and feel while editing

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#119]
- When inserting ne elements in the textual view, the outline gets collapsed
- New association are underlined red, because of the missing memberends even though there is a resolution available (and working)

**Comment by seiferma** [comment]
Outline: Check if updating the outline rather than regenerating it completely is possible. Otherwise, restore the collapsed/expanded status of the nodes and restore the previous selection.

Shown error: Solving this issue requires determining the resolvable status of an automated issue resolution based on resolvability of other resolutions. We have to introduce transitive resolvability. Most probably, it is enough to consider the missing element resolution in calculation the resolvability closure.

**Comment by seiferma** [comment]
We cannot fix the issue regarding the outline. The remaining parts of the issue are done.
