### ISSUE TITLE
Changing an IsA relation creates new relation and retains the old one

### ISSUE THREAD

**Issue by joehen** [Cooperate-Project/CooperateModelingEnvironment#121]
When changing the arguments of an isa relation, the old relation is still shown and a new reflecting the changes as well. This seems to be a merging issue.

**Comment by seiferma** [comment]
I can confirm that the issue arises during merging. Instead of detecting an add and delete event on the left comparison side, the match engine detects an add event on left AND right side. The right side should, however, never contain changes. This behavior is caused by using an outdated origin state during the three way comparison. The state is outdated because we derive it with the correct time stamp but from the master branch instead of the editor branch.

A new CDO-Xtext release includes the required fixes and will be used in further builds.
